services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nestjs-backend
    ports:
      - "4000:4000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/usr/src/app
    depends_on:
      - postgres

  frontend:
    build:
      context: ./client/frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "3000:80"
    env_file:
      - ./client/frontend/.env
    volumes:
      - ./client/frontend:/usr/src/app

  postgres:
    image: postgres:15
    container_name: nest-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nestDB
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local

